name: Check Docs

on:
  push:
    branches:
      - 'release-[0-9].[0-9]'
      - 'release-[0-9].[0-9][0-9]'
  pull_request:
    branches:
      - 'release-[0-9].[0-9]'
      - 'release-[0-9].[0-9][0-9]'

jobs:
  markdown_check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: check markdown
      run: |
        sudo npm install -g markdownlint-cli
        markdownlint -c .github/workflows/markdown_config.json ./en_US
        markdownlint -c .github/workflows/markdown_config.json ./zh_CN
        markdownlint -c .github/workflows/markdown_config.json ./ja_JP

    - name: Spell Check Repo
      uses: crate-ci/typos@v1.40.0

  directory_check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: check directory config
      run: |
        python3 ./gen.py ee | tee directory.json
        python3 .github/scripts/directory_check.py directory.json $(pwd)
