name: Check Docs

on: [push, pull_request]

jobs:
  markdown_check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: check markdown
      run: |
        sudo npm install -g markdownlint-cli
        markdownlint -c .github/workflows/markdown_config.json ./

  directory_check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: check directory config
      run: |
        python3 ./gen.py ce | tee directory.json
        python3 .github/scripts/directory_check.py directory.json $(pwd)
