name: Deploy Enterprise Docs

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - e*

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      versions: ${{ steps.set_versions.outputs.versions}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set_versions
        id: set_versions
        run: |
          current_branch=$(echo ${{ github.ref_name }})
          current_version=$(echo ${{ github.ref_name }} | sed -r "s/^(.*)-.*$/\1/")
          current_version=${current_version/e/v}
          tag_list=$(git tag | egrep "^e.*$" | xargs echo -n)
          latest_version=$(python3 .github/scripts/generate_version.py $tag_list | jq -r '.[0]')
          if [[ $current_version == $latest_version ]];
          then
            build_version_list='["'latest'","'$current_version'"]'
          else
            build_version_list='["'$current_version'"]'
          fi
          echo "versions=$build_version_list" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    strategy:
      matrix:
        version: ${{ fromJSON(needs.prepare.outputs.versions) }}
    runs-on: ubuntu-20.04
    steps:
    - name: clone docs
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: docs-files

    - name: set env
      run: |
        echo "DOCS_TYPE=enterprise" >> $GITHUB_ENV
        echo "DOCS_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "VERSION=${{ matrix.version }}" >> $GITHUB_ENV

    - name: clone ee frontend
      uses: actions/checkout@v4
      with:
        repository: 'emqx/docs-emqx-com-frontend'
        ref: next
        token: ${{ secrets.CI_GIT_TOKEN }}
        path: frontend

    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: use pnpm
      uses: pnpm/action-setup@v2
      with:
          version: 8.5.1

    - name: generate directory.json
      run: |
        cd docs-files
        ./gen.py ee | tee directory_ee.json

    - name: remove unused files
      run: |
        cd docs-files
        python3 .github/scripts/remove_unused.py directory_ee.json $(pwd)

    - name: set current emqx version
      run: |
        cd docs-files
        source current-version.env
        find ./en_US ./zh_CN -type f -name "*.md" -exec sed -i 's/@CE_VERSION@/'"$CE_VERSION"'/g' {} +
        find ./en_US ./zh_CN -type f -name "*.md" -exec sed -i 's/@EE_VERSION@/'"$EE_VERSION"'/g' {} +

    - name: move ee files
      run: |
        rm frontend/docs/en/index.md || true
        rm frontend/docs/zh/index.md || true
        rm frontend/docs/*.md || true
        rm frontend/README.md || true
        mkdir -p frontend/docs/en/${DOCS_TYPE}/${VERSION}/
        mkdir -p frontend/docs/zh/${DOCS_TYPE}/${VERSION}/
        mkdir -p frontend/docs/public/api/
        mkdir -p frontend/redoc/
        cp -r docs-files/en_US/* frontend/docs/en/${DOCS_TYPE}/${VERSION}/
        cp -r docs-files/zh_CN/* frontend/docs/zh/${DOCS_TYPE}/${VERSION}/
        cp -r docs-files/redocly/*.json frontend/redoc/
        cp docs-files/directory_ee.json frontend/docs/.vitepress/config/directory.json

    - name: generate version config
      run: |
        cd docs-files
        version_list=$(git tag | egrep "^e.*$" | xargs echo -n)
        python3 .github/scripts/generate_version.py $version_list > ../frontend/docs/public/api/${DOCS_TYPE}_versions.json

    - name: build ee docs
      run: |
        cd frontend
        pnpm install
        pnpm build

    - name: build ee redoc
      run: |
        cd frontend
        yarn global add redoc-cli
        LANGS=(zh en)
        for lang in "${LANGS[@]}"; do
          redoc-cli bundle redoc/ee-${lang}.json -t redoc/template.hbs \
            --output docs/.vitepress/dist/${lang}/enterprise/${VERSION}/admin/api-docs.html \
            --options.theme.colors.primary.main=#5e4eff \
            --options.theme.typography.headings.fontFamily='Roboto, sans-serif' \
            --options.hide-hostname --templateOptions.title "EMQX Enterprise ${VERSION} API Documentation" \
            --templateOptions.description "EMQX Enterprise ${VERSION} API Documentation" \
            --templateOptions.version "${VERSION}" \
            $(if [ "${lang}" == "zh" ]; then echo "--templateOptions.langZH \"zh\""; fi)
        done

    - name: upload ee file
      run: |
        pip3 install coscmd
        coscmd config -a ${{ secrets.TENCENT_COS_ID }} -s ${{ secrets.TENCENT_COS_KEY }} -b docs-1302406139 -r ap-shanghai
        coscmd delete -r -f en/${DOCS_TYPE}/${VERSION} || true
        coscmd delete -r -f zh/${DOCS_TYPE}/${VERSION} || true
        coscmd config -a ${{ secrets.TENCENT_COS_ID }} -s ${{ secrets.TENCENT_COS_KEY }} -b docs-1302406139 -e cos.accelerate.myqcloud.com
        coscmd upload -r frontend/docs/.vitepress/dist/ /

    - name: set tccli
      run: |
        pip3 install tccli
        tccli configure set secretId ${{ secrets.TENCENT_COS_ID }}
        tccli configure set secretKey ${{ secrets.TENCENT_COS_KEY }}
        tccli configure set region ap-shanghai

    - name: flush ee cdn
      run: |
        tccli cdn PurgePathCache --cli-unfold-argument --Paths https://docs.emqx.com/zh/${DOCS_TYPE}/${VERSION}/ https://docs.emqx.com/en/${DOCS_TYPE}/${VERSION}/ --FlushType delete
        tccli cdn PurgeUrlsCache --cli-unfold-argument --Urls https://docs.emqx.com/api/${DOCS_TYPE}_versions.json https://docs.emqx.com/sitemap_${DOCS_TYPE}_${VERSION}.xml

    - name: update ee search index
      uses: Swilder-M/docsearch-scraper-simple@next
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID_NEXT }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY_NEXT }}
      with:
        docs_type: ${{ env.DOCS_TYPE }}
        docs_version: ${{ env.VERSION }}
